---
- type: replace
  path: /instance_groups/name=shield/jobs/name=shield-agent/properties/stores?
  value:
    default:
      plugin: s3 # https://github.com/starkandwayne/shield/blob/master/plugin/s3/plugin.go
      config:
        s3_host: ((s3-host))
        s3_port: ((s3-port))
        skip_ssl_validation: ((s3-skip-ssl-validation))
        access_key_id: ((s3-access-key))
        secret_access_key: ((s3-secret-key))
        bucket: ((s3-bucket))
        prefix: ((s3-bucket-store-prefix))
