meta:
  environment: shield-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 5000-120000
  update_watch_time: 5000-120000

jobs:
  - name: shield
    networks:
      - name: shield1
        static_ips: (( static_ips(0) ))

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: shield1
  type: manual
  subnets:
  - range: 10.244.2.0/24
    name: shield1
    gateway: 10.244.2.1
    static:
      - 10.244.2.2-10.244.2.60

properties:
  shield:
    daemon:
      ssh_private_key: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAsHqfPXFIXG4qmz7n+YgisVsGQ760wc0jq9SQt/5kIdxPNjCd
        mFVxzHR6EcX3VIwarKSru7+KKIhIn69UYjZNFwy5QTRGC8dsYyYpzQN95ySEWTCn
        3QdlQfE9KNG5KgiGrHIigy7iS1eH7iSuptUq4/rGtc/2VCByoyuFZ/JU9G8wA6go
        Ar8ycZj/tWMlKpf0Kc1MSzTFYTs1VLWSRoIL4s2IXnkcXHgcKmGx6id8qfKFyWG+
        D4qQ9P94HApAejtRrJOPstuEpeDoj5J+uSwqWotKkD2eNq8NsTgtQHNmyllEjqBu
        SRpSQhcwS+B0P0W8ZYO8Y1dbuqLfgpj4kxIacwIDAQABAoIBAAKZO6EG+v7JbH0u
        tvG4rHIaGgSDWVwFLkJIdf0PlN/ew5fTrW5hy7Qr/uQmGxc2nOnv3st77YfdQdyA
        E2kCza3KNSwdne5seE8Zb8IiDAeMRRqfGcmqYzZOXA0u0WAqEfmWEKYH2bMsTccW
        6S9xshj7R1PEBSeF9soqSOOX8OJMfoyau6tWbL1PZSwJXPHdzcK90hbgSyAkcMRV
        wQeTVNtJW9zA0Ha6U4styrJRc0POOup0QqJTg38EBikTUZw8xJT8mZXWZbQTnU/l
        Y5sPLL370YrMuaVAn1d7dHCTwOlV105DeOFKIRvkQdWwlQMBSCkIDvfeNLdhS1GV
        AqIq9LECgYEA5PwdeCGjYak1v7Lx65bJlyv7sDKPqoLbQrqdpGW9AgBnppLBD0PX
        5ufK4M3VPY06D+KQpRAb+mohBbGcuL0eRan4HiPd0QVwqiv2phtxMBQ2iCvTWHvB
        mI7dlNS3cP/W+r9L9n37mPvfnKBeD0weRC+KvO1PLYz1y75LFigAG+sCgYEAxUy0
        y3NBdy/QJ30glU4aVWs6LUmfAMFO/lWDAfPGQBqUzEcpiRsRrZDCW0uAyDJXtJe3
        E4lXSkPmW9cRS18aLTxkHNENNcGDxYyKvByYRypT0vDx+uz+zwm8gZkL8lGayi4Y
        ebawyj84+dGZjaXg3CPgD6m3YPUq5vdqvkrQgZkCgYEArV07qoI9Qmlr6jE++9Dz
        22JPcf01zDC6dHD5fUgRq3xG/VRKmpYQ1h9T+JOeCLXt6aztOitSI2tKiRcJwsxc
        KP4gfiFFhUULIaubV/Oa5H3JM5uKrYk0753qoQ3TvNfWGY3Po1WKsS6xA9JepFJK
        7/DWp2c79Q6t4Y23J5UtT/UCgYARsuLZCVrLDU/36uKcYig8l2TdoSgRUkX6zML2
        zt5u67ODa7LPKM16K20z8V75FoMFoUJ8Dyr0b4jfnjhf8YUQn8U/TIWJ1/UxKH1d
        iJckcyiX2KNsZgwpmG7/lTIcJ7PiBSaO7JOJYQiEaIgEy+eS9+jmnsvjd7rEg1dh
        AKcZqQKBgQCE+DdDGubBDvD1FlDyJKa1HivS0EPnAiA249qU3CS7woaMaD59QIru
        anDiIMOQ8mlZx/ZE9yvkFoAhgfXQBfrp+XqlOh1riArDH7ANo8jtVgfa8OkjL/EW
        xReUPzb3rowTtI/4VgeOprchlWUspDoIfIlu4monWnIlx1412aRqPQ==
        -----END RSA PRIVATE KEY-----
